### ISSUE TITLE
Running `composer dump-autoload` causes a PHP Fatal error

### ISSUE THREAD

**Issue by ntwb** [humanmade/altis-seo#107]
Steps to reproduce:
1. On an Altis v8 install run `composer dump-autoload` (Based on loading custom module docs [here](https://docs.altis-dxp.com/getting-started/custom-modules/#loading-your-module))
2. Open https://subdomain.altis.dev/wp-admin/

Site does not load and the following PHP Fatal is displayed:

```
Fatal error: Uncaught Error: Class 'Yoast\WP\Duplicate_Post\Admin\Options_Page' not found in /usr/src/app/vendor/yoast/duplicate-post/duplicate-post-options.php:21 
Stack trace: 
#0 /usr/src/app/vendor/yoast/duplicate-post/duplicate-post-admin.php(13): require_once() 
# #1 /usr/src/app/vendor/yoast/duplicate-post/duplicate-post.php(104): include_once('/usr/src/app/ve...') 
# #2 /usr/src/app/vendor/altis/workflow/inc/namespace.php(67): require_once('/usr/src/app/ve...') 
# #3 /usr/src/app/wordpress/wp-includes/class-wp-hook.php(292): Altis\Workflow\load_duplicate_posts('') 
# #4 /usr/src/app/wordpress/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array) 
# #5 /usr/src/app/wordpress/wp-includes/plugin.php(484): WP_Hook->do_action(Array) 
# #6 /usr/src/app/wordpress/wp-settings.php(358): do_action('muplugins_loade...') 
# #7 /usr/src/app/wp-config.php(80): require_once('/usr/src/app/wo...') 
# #8 /usr/src/app/wordpress/wp-load.php(42): require_once('/usr/src/app/wp...') 
# #9 /usr/src/app/wordpress/wp-admin/admin.php(34): require_once('/usr/src/app/wo...') 
# #10 /usr/src/app/wordpress/wp-admin/index.php(10): require_once('/usr/src/app/wo...') 
# #11 {main} thrown in /usr/src/app/vendor/yoast/duplicate-post/duplicate-post-options.php on line 21
Fatal error: Uncaught Error: Class 'Yoast\WP\Duplicate_Post\Admin\Options_Page' not found in /usr/src
```

Acceptance criteria:

- [ ] ...

**Comment by roborourke** [comment]
As far as I can tell running `composer dump-autoload` ends up skipping all 2nd level dependencies that are not the standard type e.g. `wordpress-plugin` or `wordpress-muplugin`.

As a temporary work around you can use `composer install` to regenerate autoload files for now.
